### ISSUE TITLE
AssertionError in MDF.to_dataframe when raster is 1-element ndarray

### ISSUE THREAD

**Issue by morbult** [danielhrisca/asammdf#1155]
There is a bug in to_dataframe when supplying raster as a 1-element ndarray. Given an ndarray, it should (I guess) use that as a raster. But the code first tries to convert it to a float, which currently works if it is a _1-element_ ndarray (however this behaviour is deprecated and will later raise error). So, currently, given `raster=np.array([0])`, to_dataframe treats it not as a raster array, but as a float step value = 0.0, and that causes an error since a step value must be > 0.

Reproduce it with

```python
import asammdf
import numpy as np
import pandas as pd

df = pd.DataFrame({n: [1.0] for n in 'abc'})
mdf = asammdf.MDF(version='4.10')  # same behaviour for '3.30'
mdf.append(df)
mdf.to_dataframe(raster=np.array([0.0]))
```

The last line fails with

```python
Traceback (most recent call last):

  line 9
    mdf.to_dataframe(raster=raster)

  File ~\asammdf\src\asammdf\mdf.py:4831 in to_dataframe
    assert raster > 0

AssertionError
```

This can also give unexpected results when a channel name is directly convertable to float (like "0") and you give that name as the raster argument. For example:
```python
df = pd.DataFrame({n: [1.0] for n in '012'})
mdf = asammdf.MDF(version='4.10')
mdf.append(df)
mdf.to_dataframe(raster='0')  # AssertionError
```

**Comment by morbult** [comment]
Solution suggested in #1157

**Comment by danielhrisca** [comment]
Thanks for reporting, I've pushed a fix to the development branch

**Comment by morbult** [comment]
The example above still fails because the raster check was only changed in resample and iter_to_dataframe.

Not sure you saw but I already made a PR with a suggest fix. Also including a test case to catch this bug, and the one in #1156.

**Comment by danielhrisca** [comment]
right, I've made the same change to `to_dataframe`

**Comment by morbult** [comment]
It works, just a correction needed in the error message. raster must be _greater than_ 0 if it's a scalar value
