### ISSUE TITLE
Unable to read dat-file, struct.error: unpack_from requires a buffer of at least 73880 bytes

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#387]
# Python version
python=3.6.5
asammdf=5.21.0

# Code 

with MDF(file,remove_source_from_channel_names=True, use_display_names=True) as mdf_file:

   df = mdf_file.to_dataframe(Labels.name.tolist(),time_from_zero=False) 

  
  ## Traceback
Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 266, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "\anaconda3\lib\site-packages\asammdf\mdf.py", line 119, in __init__
    self._mdf = MDF3(name, **kwargs)
  File "\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 204, in __init__
    self._read(mapped=True)
  File "\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 855, in _read
    cc_map=self._cc_map,
  File "\anaconda3\lib\site-packages\asammdf\blocks\v2_v3_blocks.py", line 279, in __init__
    mapped=mapped,
  File "\anaconda3\lib\site-packages\asammdf\blocks\v2_v3_blocks.py", line 984, in __init__
    "<" + "d32s" * nr, block, v23c.CC_COMMON_SHORT_SIZE
struct.error: unpack_from requires a buffer of at least 73880 bytes

Details: 2020-07-21, 20:29:19
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 266, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "\anaconda3\lib\site-packages\asammdf\mdf.py", line 119, in __init__
    self._mdf = MDF3(name, **kwargs)
  File "\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 204, in __init__
    self._read(mapped=True)
  File "\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 855, in _read
    cc_map=self._cc_map,
  File "\anaconda3\lib\site-packages\asammdf\blocks\v2_v3_blocks.py", line 279, in __init__
    mapped=mapped,
  File "\anaconda3\lib\site-packages\asammdf\blocks\v2_v3_blocks.py", line 984, in __init__
    "<" + "d32s" * nr, block, v23c.CC_COMMON_SHORT_SIZE
struct.error: unpack_from requires a buffer of at least 73880 bytes

--------------------------------------------------------------------------------
  File "\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 822, in open
    self.open_file(event)
  File "\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 862, in open_file
    self._open_file(file_name)
  File "\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 838, in _open_file
    self,
  File "\anaconda3\lib\site-packages\asammdf\gui\widgets\file.py", line 159, in __init__
    progress=progress,
  File "\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 231, in run_thread_with_progress
    raise Exception(thr.error)
  
# Description

I'm trying to read a dat-file with the code above and get this struct.error. This will also appear if I try to load the file using the GUI. Therefore I can't provide a scrambled file. Reading the file using TurboLab or MDA will work fine.

**Comment by Lama09** [comment]
Any idea?

**Comment by danielhrisca** [comment]
Can you the file integrity with MDFValidator?

**Comment by Lama09** [comment]
The MDFValidator comes up with errors, so the format doesn't seems to be valid. Running the file with TurboLab 7.0, MDA V7.2 or MDA 8.4 is possible. The issue is, that I do got hundreds of this type of files which I'm now unable to read within my python tool chain.

Do you see any chance to find a solution or at least catch this error by an MdfException?

**Comment by danielhrisca** [comment]
@Lama09 please try the new development code

**Comment by danielhrisca** [comment]
ping @Lama09

**Comment by oblamine** [comment]
Hello, 
i have the same problem here with MF4 files, 
i have plenty of small files, i treat one by one but for some of them i have this issue.
max file size is about 1.5 Mo 
python ->3.6.8
asammdf -> 5.10.3
@danielhrisca which version resolved this bug (if it was resolved)
thank you

**Comment by danielhrisca** [comment]
@oblamine you may try with version 5.23.1. If you still have the problem can you send one of the files for analysis?

**Comment by Lama09** [comment]
@danielhrisca,
I'm very sorry for my late response. I tested a file with version 5.23.1 and the issue is fixed.   👍 Once again, many thanks for your package and your help.

**Comment by oblamine** [comment]
> @oblamine you may try with version 5.23.1. If you still have the problem can you send one of the files for analysis?

Thanks for you answer, i have tried the version 5.23.1, but i still have the error. the only difference is 24 bytes --> 16 bytes. below the error. 
Thank you. 

`error: unpack_from requires a buffer of at least 16 bytes
error                                     Traceback (most recent call last)
in engine
----> 1 mdf = MDF(path)

/home/cdsw/.local/lib/python3.6/site-packages/asammdf/mdf.py in __init__(self, name, version, **kwargs)
    128                 self._mdf = MDF3(name, **kwargs)
    129             elif version in MDF4_VERSIONS:
--> 130                 self._mdf = MDF4(name, **kwargs)
    131             elif version in MDF2_VERSIONS:
    132                 self._mdf = MDF2(name, **kwargs)

/home/cdsw/.local/lib/python3.6/site-packages/asammdf/blocks/mdf_v4.py in __init__(self, name, version, **kwargs)
    392                         self._file = mmap.mmap(x.fileno(), 0, access=mmap.ACCESS_READ)
    393                         self._from_filelike = False
--> 394                         self._read(mapped=True)
    395 
    396                         self._file.close()

/home/cdsw/.local/lib/python3.6/site-packages/asammdf/blocks/mdf_v4.py in _read(self, mapped)
    659                 mapped=mapped,
    660                 total_size=total_size,
--> 661                 inval_total_size=inval_total_size,
    662             )
    663 

/home/cdsw/.local/lib/python3.6/site-packages/asammdf/blocks/mdf_v4.py in _get_data_blocks_info(self, address, stream, block_type, mapped, total_size, inval_total_size)
   2073                         mapped,
   2074                         total_size,
-> 2075                         inval_total_size,
   2076                     )
   2077         else:

/home/cdsw/.local/lib/python3.6/site-packages/asammdf/blocks/mdf_v4.py in _get_data_blocks_info(self, address, stream, block_type, mapped, total_size, inval_total_size)
   1867                             addr = dl[f"data_block_addr{i}"]
   1868 
-> 1869                             id_string, _1, block_len = COMMON_SHORT_uf(stream, addr)
   1870                             # can be a DataBlock
   1871                             if id_string == block_type:

error: unpack_from requires a buffer of at least 16 bytes`

**Comment by danielhrisca** [comment]
@oblamine do you see errors in mdfvalidator? Also can you send a file (you can scramble it first) for analysis?

**Comment by danielhrisca** [comment]
@oblamine @Lama09 please check with asammdf 6.0.1
